/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Reservation = IDL.Record({
  'id' : IDL.Nat,
  'seating' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'occasion' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'guests' : IDL.Nat,
});
export const Review = IDL.Record({
  'dish' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getReservationsByPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTopReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'submitReservation' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'submitReview' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'subscribeNewsletter' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'duplicate' : IDL.Null, 'success' : IDL.Null })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Reservation = IDL.Record({
    'id' : IDL.Nat,
    'seating' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'occasion' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'guests' : IDL.Nat,
  });
  const Review = IDL.Record({
    'dish' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getReservationsByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTopReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'submitReservation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'submitReview' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'subscribeNewsletter' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'duplicate' : IDL.Null, 'success' : IDL.Null })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };